export enum ScreeningState {
    CREATED = "CREATED",
    SUBMITTED = "SUBMITTED",
    REVIEWED = "REVIEWED",
    APPROVED = "APPROVED",
    FINAL_SUBMITTED = " FINAL_PUBLICATION",
    SCHEDULED = "SCHEDULED",
    REJECTED = "REJECTED",
    COMPLETED = "COMPLETED",
    CANCELLED = "CANCELLED",
}
