export enum ProgramState {
    CREATED = "CREATED",
    SUBMISSION = "SUBMISSION",
    ASSIGNMENT = "ASSIGNMENT",
    REVIEW = "REVIEW",
    SCHEDULING = "SCHEDULING",
    FINAL_PUBLICATION = "FINAL_PUBLICATION",
    DECISION = "DECISION",
    ANNOUNCED = "ANNOUNCED",
}
