-- =========================
-- USERS
-- =========================
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(64)   NOT NULL,
    password_hash   VARCHAR(1000) NOT NULL,
    full_name       VARCHAR(120)  NOT NULL,
    base_role       VARCHAR(20)   NOT NULL,
    active          BOOLEAN       NOT NULL,
    failed_attempts INT           NOT NULL
);

CREATE UNIQUE INDEX uk_users_username ON users(username);


-- =========================
-- PROGRAMS
-- =========================
CREATE TABLE programs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(120)  NOT NULL,
    description     VARCHAR(2000),
    start_date      DATE,
    end_date        DATE,
    state           VARCHAR(20)   NOT NULL,
    creator_user_id BIGINT        NOT NULL,

    CONSTRAINT fk_program_creator
        FOREIGN KEY (creator_user_id) REFERENCES users(id)
);


-- =========================
-- PROGRAM PROGRAMMERS
-- =========================
CREATE TABLE program_programmers (
    program_id BIGINT NOT NULL,
    user_id    BIGINT NOT NULL,

    CONSTRAINT pk_program_programmers PRIMARY KEY (program_id, user_id),
    CONSTRAINT fk_pgpr_program FOREIGN KEY (program_id) REFERENCES programs(id),
    CONSTRAINT fk_pgpr_user    FOREIGN KEY (user_id)    REFERENCES users(id)
);


-- =========================
-- PROGRAM STAFF
-- =========================
CREATE TABLE program_staff (
    program_id BIGINT NOT NULL,
    user_id    BIGINT NOT NULL,

    CONSTRAINT pk_program_staff PRIMARY KEY (program_id, user_id),
    CONSTRAINT fk_pgstaff_program FOREIGN KEY (program_id) REFERENCES programs(id),
    CONSTRAINT fk_pgstaff_user    FOREIGN KEY (user_id)    REFERENCES users(id)
);


-- =========================
-- SCREENINGS
-- =========================
CREATE TABLE screenings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    program_id      BIGINT NOT NULL,
    submitter_id    BIGINT NOT NULL,
    title           VARCHAR(200)  NOT NULL,
    genre           VARCHAR(100),
    description     VARCHAR(4000),
    room            VARCHAR(100),
    scheduled_time  DATE,

    screening_state VARCHAR(20) NOT NULL,

    staff_member_id BIGINT,
    submitted_time  DATE,
    reviewed_time   DATE,

    CONSTRAINT fk_screening_program
        FOREIGN KEY (program_id) REFERENCES programs(id),
    CONSTRAINT fk_screening_submitter
        FOREIGN KEY (submitter_id) REFERENCES users(id),
    CONSTRAINT fk_screening_staff
        FOREIGN KEY (staff_member_id) REFERENCES users(id)
);



CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id BIGINT NOT NULL,
    action VARCHAR(50) NOT NULL,
    target VARCHAR(255),
    timestamp TIMESTAMP NOT NULL
);

-- =========================
-- SCREENINGS INDEXES
-- =========================
CREATE INDEX idx_screening_program   ON screenings(program_id);
CREATE INDEX idx_screening_submitter ON screenings(submitter_id);
CREATE INDEX idx_screening_staff     ON screenings(staff_member_id);
