-- =========================
-- USERS
-- =========================
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(64)   NOT NULL,
    password_hash   VARCHAR(1000) NOT NULL,
    full_name       VARCHAR(120)  NOT NULL,
    base_role       VARCHAR(20)   NOT NULL,
    active          BOOLEAN       NOT NULL,
    failed_attempts INT           NOT NULL,

    -- Για requirements: invalidate previous token, force logout, invalidate on password/username change
    current_jti     VARCHAR(36),
    last_login_at   TIMESTAMP
);

CREATE UNIQUE INDEX uk_users_username ON users(username);


-- =========================
-- PROGRAMS
-- =========================
CREATE TABLE programs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name            VARCHAR(120)  NOT NULL,
    description     VARCHAR(2000) NOT NULL,
    start_date      DATE          NOT NULL,
    end_date        DATE          NOT NULL,
    state           VARCHAR(20)   NOT NULL,

    creator_user_id BIGINT        NOT NULL,

    -- απαιτείται creation date
    created_time    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_program_creator
        FOREIGN KEY (creator_user_id) REFERENCES users(id)
);

CREATE UNIQUE INDEX uk_programs_name ON programs(name);


-- =========================
-- PROGRAM PROGRAMMERS
-- =========================
CREATE TABLE program_programmers (
    program_id BIGINT NOT NULL,
    user_id    BIGINT NOT NULL,

    CONSTRAINT pk_program_programmers PRIMARY KEY (program_id, user_id),
    CONSTRAINT fk_pgpr_program FOREIGN KEY (program_id) REFERENCES programs(id),
    CONSTRAINT fk_pgpr_user    FOREIGN KEY (user_id)    REFERENCES users(id)
);


-- =========================
-- PROGRAM STAFF
-- =========================
CREATE TABLE program_staff (
    program_id BIGINT NOT NULL,
    user_id    BIGINT NOT NULL,

    CONSTRAINT pk_program_staff PRIMARY KEY (program_id, user_id),
    CONSTRAINT fk_pgstaff_program FOREIGN KEY (program_id) REFERENCES programs(id),
    CONSTRAINT fk_pgstaff_user    FOREIGN KEY (user_id)    REFERENCES users(id)
);


-- =========================
-- SCREENINGS
-- =========================
CREATE TABLE screenings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    program_id      BIGINT NOT NULL,
    submitter_id    BIGINT NOT NULL,

    -- Film info stored inside screening (spec)
    title            VARCHAR(200)  NOT NULL,
    genres           VARCHAR(500),
    cast_names       VARCHAR(2000),   -- ✅ renamed from "cast"
    duration_minutes INT,

    description      VARCHAR(4000),

    auditorium_name  VARCHAR(100),

    -- scheduling fields (TIMESTAMP, όχι DATE)
    start_time       TIMESTAMP,
    end_time         TIMESTAMP,

    screening_state  VARCHAR(30) NOT NULL,

    staff_member_id  BIGINT,

    created_time     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    submitted_time   TIMESTAMP,
    reviewed_time    TIMESTAMP,

    review_score     INT,
    review_comments  VARCHAR(4000),

    approved_notes       VARCHAR(2000),

    final_submitted_time TIMESTAMP,
    final_locked         BOOLEAN NOT NULL DEFAULT FALSE,

    rejection_reason VARCHAR(2000),

    CONSTRAINT fk_screening_program
        FOREIGN KEY (program_id) REFERENCES programs(id),
    CONSTRAINT fk_screening_submitter
        FOREIGN KEY (submitter_id) REFERENCES users(id),
    CONSTRAINT fk_screening_staff
        FOREIGN KEY (staff_member_id) REFERENCES users(id),

    CONSTRAINT chk_screening_times
        CHECK (start_time IS NULL OR end_time IS NULL OR end_time >= start_time)
);

CREATE INDEX idx_screening_program   ON screenings(program_id);
CREATE INDEX idx_screening_submitter ON screenings(submitter_id);
CREATE INDEX idx_screening_staff     ON screenings(staff_member_id);
CREATE INDEX idx_screening_starttime ON screenings(start_time);


-- =========================
-- AUDIT LOGS
-- =========================
CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id BIGINT NOT NULL,
    action VARCHAR(50) NOT NULL,
    target VARCHAR(255),
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_audit_actor
        FOREIGN KEY (actor_user_id) REFERENCES users(id)
);

CREATE INDEX idx_audit_actor ON audit_logs(actor_user_id);
CREATE INDEX idx_audit_time  ON audit_logs(timestamp);

-- AUDIT_LOGS: actor_user_id πρέπει να γίνει nullable για να δουλέψει SET NULL
ALTER TABLE audit_logs ALTER COLUMN actor_user_id SET NULL;

-- Ρίξε το παλιό FK
ALTER TABLE audit_logs DROP CONSTRAINT fk_audit_actor;

-- Ξαναφτιάξε FK με ON DELETE SET NULL
ALTER TABLE audit_logs
  ADD CONSTRAINT fk_audit_actor
  FOREIGN KEY (actor_user_id)
  REFERENCES users(id)
  ON DELETE SET NULL;
