-- =========================
-- USERS
-- =========================
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(64)  NOT NULL,
    passwordHash  VARCHAR(1000) NOT NULL,
    fullName      VARCHAR(120) NOT NULL,
    baseRole      VARCHAR(20)  NOT NULL,
    active        BOOLEAN      NOT NULL,
    failedAttempts INT         NOT NULL
);

-- Unique index στο username (όπως @Index + unique = true)
CREATE UNIQUE INDEX uk_users_username ON users(username);


-- =========================
-- PROGRAMS
-- =========================
CREATE TABLE programs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(120)  NOT NULL,
    description  VARCHAR(2000),
    startDate    DATE,
    endDate      DATE,
    state        VARCHAR(20)   NOT NULL,
    creatorUserId BIGINT       NOT NULL,

    CONSTRAINT fk_program_creator
        FOREIGN KEY (creatorUserId) REFERENCES users(id)
);


-- =========================
-- PROGRAM PROGRAMMERS (Set<Long> programmers)
-- =========================
CREATE TABLE ProgramProgrammers (
    programId BIGINT NOT NULL,
    userId    BIGINT NOT NULL,

    CONSTRAINT pk_ProgramProgrammers PRIMARY KEY (programId, userId),
    CONSTRAINT fk_prog_prog_program
        FOREIGN KEY (programId) REFERENCES programs(id),
    CONSTRAINT fk_prog_prog_user
        FOREIGN KEY (userId) REFERENCES users(id)
);


-- =========================
-- PROGRAM STAFF (Set<Long> staff)
-- =========================
CREATE TABLE programStaff (
    programId BIGINT NOT NULL,
    userId    BIGINT NOT NULL,

    CONSTRAINT pk_programStaff PRIMARY KEY (programId, userId),
    CONSTRAINT fk_prog_staff_program
        FOREIGN KEY (programId) REFERENCES programs(id),
    CONSTRAINT fk_prog_staff_user
        FOREIGN KEY (userId) REFERENCES users(id)
);


-- =========================
-- SCREENINGS
-- =========================
CREATE TABLE Screenings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    programId     BIGINT NOT NULL,
    submitterId   BIGINT NOT NULL,
    title         VARCHAR(200)  NOT NULL,
    genre         VARCHAR(100),
    description   VARCHAR(4000),
    room          VARCHAR(100),
    scheduledTime DATE,

    screeningState VARCHAR(20) NOT NULL,

    staffMemberId BIGINT,
    submittedTime DATE,
    reviewedTime  DATE,

    CONSTRAINT fk_screening_program
        FOREIGN KEY (programId)   REFERENCES programs(id),
    CONSTRAINT fk_screening_submitter
        FOREIGN KEY (submitterId) REFERENCES users(id),
    CONSTRAINT fk_screening_staff
        FOREIGN KEY (staffMemberId) REFERENCES users(id)
);

-- Indexes όπως στο @Table(indexes = ...)
CREATE INDEX idScreeningsProgram  ON Screenings(programId);
CREATE INDEX idScreeningsSubmitter ON Screenings(submitterId);
CREATE INDEX idScreeningsStaff     ON Screenings(staffMemberId);
